### ISSUE TITLE
toctree depth

### ISSUE THREAD

**Issue by JacquesLucke** [JacquesLucke/animation_nodes_manual#16] opened 2016-05-29 21:03 UTC
How deep should the toctree in the index.rst pages be?
This looks very unorganised: http://animation-nodes-manual.readthedocs.io/en/latest/user_guide/nodes/index.html

Maybe there should only be the category names, what do you think?

**Comment by hapit** [comment] 2016-05-29 22:00
You are right. The depth is to high.
The problem is, the toctree shows categories and sections. 
With the depth of 2 it only shows Categories and Nodes.

**Comment by hapit** [comment] 2017-07-26 10:38
After one year with no comments, I think everybody is happy with the depth of 2.
I close the issue.

**Closed by hapit** 2017-07-26 10:38 UTC
